# Generated by Django 4.2.11 on 2024-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
