# Generated by Django 5.0.3 on 2024-05-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_market_address_alter_market_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='countMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_count_method', to='base.countmethod'),
        ),
    ]
