# Generated by Django 5.0.3 on 2024-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_countmethod_product_countmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
